baseURL = 'https://pedrobyjoao.github.io/my-blog/'
languageCode = 'en-us'
title = 'JP, an ape'
theme = 'typo'

[taxonomies]
  tag = 'tags'

[params]
  # Meta description
  description = "A Reality Blog"

  # Appearance settings
  theme = 'auto'
  colorPalette = 'default'
  hideHeader = false

  # Intro on main page, content is markdown
  homeIntroTitle = "Hi, conscious being"
  homeIntroContent = """
  What am I? What do I live for? Am I still here for love? For pleasure? For fun?

  Bah.. who knows. This human subjectivity is too complex for me. I'm just an ape
  that sometimes tries to understand reality without success.

  In this blog, I'll express my thoughts about reality, computer science and art.

  How do I feel while creating this blog? As Neal Cassady would answer: "YES YES YES!"

  Currently reading: 
  - "On The Road", Jack Kerouac.
  - "Berserk", Kentaro Miura.
  - "Meditations", Marcus Aurelius.
  """

  # Collection to display on home
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'

  # Lists parameters
  paginationSize = 100
  listSummaries = true
  listDateFormat = '2 Jan 2006'

  # Breadcrumbs
  breadcrumbs = true

# Social icons
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/user/"

[[params.social]]
  name = "github"
  url = "https://github.com/PedrobyJoao"

# Main menu pages
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Books"
  url = "/books/"
  weight = 3

[[menu.main]]
  name = "Poems"
  url = "/poems/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

# Syntax highlight on code blocks
[markup.highlight]
  style = 'algol'

# Giscus comments
[params.giscus]
  enable = false
  repo = "user/repo"
  repoId = "repoId"
  category = "General"
  categoryId = "categoryId"
  mapping = "pathname"
  theme = "preferred_color_scheme"
