baseURL = 'https://apemortalis.com'
languageCode = 'en-us'
title = 'JP, an ape'
theme = 'typo'

[taxonomies]
  tag = 'tags'

[params]
  # Meta description
  description = "A Reality Blog"

  # Appearance settings
  theme = 'auto'
  colorPalette = 'default'
  hideHeader = false

  # Intro on main page, content is markdown
  homeIntroTitle = "Hi, conscious being"
  homeIntroContent = """
  Living the randomness

  Meeting random human beings  
  Working in random jobs  
  Dreaming random dreams

  Laughing to random jokes  
  Listening to random songs  
  Jamming random notes

  Sleeping in random places  
  Eating random food  
  Dancing random dances

  Crying, missing the ones that I love.  
  Smiling, experiencing the unknown cosmic drips of life.

  -----------------------------

Projects:
- [Lambda calculus evaluation](https://lambdaeval.apemortalis.com)


Currently reading: 
- How Music Works, David Byrne
- Mind illuminated

  """

  # Collection to display on home
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'

  # Lists parameters
  paginationSize = 100
  listSummaries = false
  listDateFormat = '2 Jan 2006'

  # Breadcrumbs
  breadcrumbs = true

# Social icons
# [[params.social]]
#   name = "linkedin"
#   url = "https://pedrobyjoao.github.io/about"

[[params.social]]
  name = "github"
  url = "https://github.com/PedrobyJoao"

# Menu pages
[[params.menu]]
    name = "home"
    url = "/"

[[params.menu]]
    name = "Posts"
    url = "/posts"

[[params.menu]]
    name = "Books"
    url = "/books"

[[params.menu]]
    name = "Poems"
    url = "/poems"

# Syntax highlight on code blocks
[markup.highlight]
  style = 'algol'

# Giscus comments
[params.giscus]
  enable = false
  repo = "user/repo"
  repoId = "repoId"
  category = "General"
  categoryId = "categoryId"
  mapping = "pathname"
  theme = "preferred_color_scheme"
